kind: ConfigMap
apiVersion: v1
metadata:
  #creationTimestamp: 2016-02-18T19:14:38Z
  name: nginx-config
  namespace: eo-services
data:
  # example of a complex property defined using --from-file
  nginx.conf: |-
    worker_processes  1;  ## Default: 1
    #error_log /var/log/nginx/error.log warn;
    #pid /var/run/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  1024;  ## Default: 1024
    }

    http {
      upstream template-svce {
          server template-svce:8080;
      }

      server {
          listen 80;

          location / {
              proxy_pass http://template-svce;
          }
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: eo-services
spec:
  selector:
    app: template-service
    tier: frontend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80  # container port
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eo-services
spec:
  selector:
    matchLabels:
      app: template-service
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: template-service
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
        volumeMounts:
        - name: config-volume
          #mountPath: /etc/nginx
          # mounting an individual file as mounting the whole directory breaks sub-directories used
          # for log files.
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config # include all files in the ConfigMap at the mount point
              
