jobs:
  include:
    - stage: generate docs
      # if: branch = master

      # Assume that 'docker' service is stated at the Travis global level. It seems that re-stating it here confuses Travis.
      # services:
      #   - docker

      before_install:
        - mkdir -p output
        - docker pull asciidoctor/docker-asciidoctor

      script:
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output docs/index.adoc
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output docs/index.adoc

      after_error:
        - docker logs asciidoc-to-html
        - docker logs asciidoc-to-pdf

      after_failure:
        - docker logs asciidoc-to-html
        - docker logs asciidoc-to-pdf

      after_success:
        - mkdir tmp ; cd tmp
        - git clone --branch gh-pages --single-branch "https://${GH_TOKEN}@${GH_REF}" repos
        - cd repos
        - mkdir -p current
        - cp -r ../../output/* current
        - if [ ! -e index.html ]; then cp ../../docs/gh-page-root.html index.html; fi
        - git config user.name "${GH_USER_NAME}"
        - git config user.email "${GH_USER_NAME}"
        - git add . ; git commit -m "Deploy to GitHub Pages"
        - git push
